; ModuleID = 'output/flv.c'
source_filename = "output/flv.c"
target datalayout = "e-m:m-p:32:32-i8:8:32-i16:16:32-i64:64-n32-S64"
target triple = "dsp"

%struct.cli_output_t = type { i32 (i8*, i8**, %struct.cli_output_opt_t*)*, i32 (i8*, %struct.x264_param_t*)*, i32 (i8*, %struct.x264_nal_t*)*, i32 (i8*, i8*, i32, %struct.x264_picture_t*)*, i32 (i8*, i64, i64)* }
%struct.cli_output_opt_t = type { i32 }
%struct.x264_param_t = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, %struct.anon, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i8*, [16 x i8], [16 x i8], [16 x i8], [16 x i8], [64 x i8], [64 x i8], [64 x i8], [64 x i8], void (i8*, i32, i8*, i8*)*, i8*, i32, i32, i8*, %struct.anon.0, %struct.anon.1, %struct.anon.2, i32, %struct.anon.3, %struct.anon.4, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i8*, i8*, i32, i32, i32, i32, i32, void (i8*)*, void (%struct.x264_t*, %struct.x264_nal_t*, i8*)*, i8* }
%struct.anon = type { i32, i32, i32, i32, i32, i32, i32, i32, i32 }
%struct.anon.0 = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, float, float, i32, i32, i32, [2 x i32], i32, i32 }
%struct.anon.1 = type { i32, i32, i32, i32, i32, i32, float, float, float, i32, i32, float, float, float, i32, i32, float, i32, i32, i32, i8*, i32, i8*, float, float, float, %struct.x264_zone_t*, i32, i8* }
%struct.x264_zone_t = type { i32, i32, i32, i32, float, %struct.x264_param_t* }
%struct.anon.2 = type { i32, i32, i32, i32 }
%struct.anon.3 = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i64, i64 }
%struct.anon.4 = type { i32, i32, i32 }
%struct.x264_t = type opaque
%struct.x264_nal_t = type { i32, i32, i32, i32, i32, i32, i8*, i32 }
%struct.x264_picture_t = type { i32, i32, i32, i32, i64, i64, %struct.x264_param_t*, %struct.x264_image_t, %struct.x264_image_properties_t, %struct.x264_hrd_t, %struct.x264_sei_t, i8* }
%struct.x264_image_t = type { i32, i32, [4 x i32], [4 x i8*] }
%struct.x264_image_properties_t = type { float*, void (i8*)*, i8*, void (i8*)*, double, double, [3 x double], double }
%struct.x264_hrd_t = type { double, double, double, double }
%struct.x264_sei_t = type { i32, %struct.x264_sei_payload_t*, void (i8*)* }
%struct.x264_sei_payload_t = type { i32, i32, i8* }
%struct.flv_buffer = type { i8*, i32, i32, %struct._IO_FILE*, i64 }
%struct._IO_FILE = type { i32, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, %struct._IO_marker*, %struct._IO_FILE*, i32, i32, i32, i16, i8, [1 x i8], i8*, i64, %struct._IO_codecvt*, %struct._IO_wide_data*, %struct._IO_FILE*, i8*, i32, i32, [40 x i8] }
%struct._IO_marker = type opaque
%struct._IO_codecvt = type opaque
%struct._IO_wide_data = type opaque
%struct.stat = type { i64, i16, i32, i32, i32, i32, i32, i64, i16, i64, i32, i64, %struct.timespec, %struct.timespec, %struct.timespec, i64 }
%struct.timespec = type { i32, i32 }
%struct.stat64 = type { i64, i32, i32, i32, i32, i32, i32, i64, i32, i64, i32, i64, %struct.timespec, %struct.timespec, %struct.timespec, i64 }

@flv_output = hidden local_unnamed_addr constant %struct.cli_output_t { i32 (i8*, i8**, %struct.cli_output_opt_t*)* @open_file, i32 (i8*, %struct.x264_param_t*)* @set_param, i32 (i8*, %struct.x264_nal_t*)* @write_headers, i32 (i8*, i8*, i32, %struct.x264_picture_t*)* @write_frame, i32 (i8*, i64, i64)* @close_file }, align 4
@.str = private unnamed_addr constant [4 x i8] c"FLV\00", align 1
@.str.1 = private unnamed_addr constant [11 x i8] c"onMetaData\00", align 1
@.str.2 = private unnamed_addr constant [6 x i8] c"width\00", align 1
@.str.3 = private unnamed_addr constant [7 x i8] c"height\00", align 1
@.str.4 = private unnamed_addr constant [10 x i8] c"framerate\00", align 1
@.str.5 = private unnamed_addr constant [13 x i8] c"videocodecid\00", align 1
@.str.6 = private unnamed_addr constant [9 x i8] c"duration\00", align 1
@.str.7 = private unnamed_addr constant [9 x i8] c"filesize\00", align 1
@.str.8 = private unnamed_addr constant [14 x i8] c"videodatarate\00", align 1
@.str.9 = private unnamed_addr constant [1 x i8] zeroinitializer, align 1
@.str.10 = private unnamed_addr constant [4 x i8] c"flv\00", align 1
@.str.11 = private unnamed_addr constant [23 x i8] c"initial delay %lld ms\0A\00", align 1
@.str.12 = private unnamed_addr constant [98 x i8] c"duplicate DTS %lld generated by rounding\0A               decoding framerate cannot exceed 1000fps\0A\00", align 1
@.str.13 = private unnamed_addr constant [101 x i8] c"duplicate CTS %lld generated by rounding\0A               composition framerate cannot exceed 1000fps\0A\00", align 1

; Function Attrs: nounwind
define internal i32 @open_file(i8* %psz_filename, i8** nocapture %p_handle, %struct.cli_output_opt_t* nocapture readonly %opt) #0 {
entry:
  %call = tail call noalias dereferenceable_or_null(144) i8* @calloc(i32 1, i32 144) #6
  %tobool = icmp eq i8* %call, null
  br i1 %tobool, label %cleanup11, label %if.then

if.then:                                          ; preds = %entry
  %call1 = tail call %struct.flv_buffer* @flv_create_writer(i8* %psz_filename) #6
  %tobool2 = icmp eq %struct.flv_buffer* %call1, null
  br i1 %tobool2, label %if.end9, label %if.then3

if.then3:                                         ; preds = %if.then
  tail call void @flv_put_tag(%struct.flv_buffer* nonnull %call1, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i32 0, i32 0)) #6
  tail call void @flv_put_byte(%struct.flv_buffer* nonnull %call1, i8 zeroext 1) #6
  tail call void @flv_put_byte(%struct.flv_buffer* nonnull %call1, i8 zeroext 1) #6
  tail call void @flv_put_be32(%struct.flv_buffer* nonnull %call1, i32 9) #6
  tail call void @flv_put_be32(%struct.flv_buffer* nonnull %call1, i32 0) #6
  %call.i = tail call i32 @flv_flush_data(%struct.flv_buffer* nonnull %call1) #6
  %tobool5 = icmp eq i32 %call.i, 0
  br i1 %tobool5, label %if.then6, label %if.end

if.then6:                                         ; preds = %if.then3
  %c7 = bitcast i8* %call to %struct.flv_buffer**
  store %struct.flv_buffer* %call1, %struct.flv_buffer** %c7, align 8, !tbaa !2
  %use_dts_compress = getelementptr inbounds %struct.cli_output_opt_t, %struct.cli_output_opt_t* %opt, i32 0, i32 0
  %0 = load i32, i32* %use_dts_compress, align 4, !tbaa !10
  %b_dts_compress = getelementptr inbounds i8, i8* %call, i32 132
  %1 = bitcast i8* %b_dts_compress to i32*
  store i32 %0, i32* %1, align 4, !tbaa !12
  br label %cleanup11

if.end:                                           ; preds = %if.then3
  %fp = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %call1, i32 0, i32 3
  %2 = load %struct._IO_FILE*, %struct._IO_FILE** %fp, align 4, !tbaa !13
  %call8 = tail call i32 @fclose(%struct._IO_FILE* %2)
  %data = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %call1, i32 0, i32 0
  %3 = load i8*, i8** %data, align 8, !tbaa !15
  tail call void @free(i8* %3) #6
  %4 = bitcast %struct.flv_buffer* %call1 to i8*
  tail call void @free(i8* %4) #6
  br label %if.end9

if.end9:                                          ; preds = %if.then, %if.end
  tail call void @free(i8* nonnull %call) #6
  br label %cleanup11

cleanup11:                                        ; preds = %entry, %if.end9, %if.then6
  %storemerge = phi i8* [ %call, %if.then6 ], [ null, %if.end9 ], [ null, %entry ]
  %retval.1 = phi i32 [ 0, %if.then6 ], [ -1, %if.end9 ], [ -1, %entry ]
  store i8* %storemerge, i8** %p_handle, align 4, !tbaa !16
  ret i32 %retval.1
}

; Function Attrs: nounwind
define internal i32 @set_param(i8* nocapture %handle, %struct.x264_param_t* nocapture readonly %p_param) #0 {
entry:
  %c1 = bitcast i8* %handle to %struct.flv_buffer**
  %0 = load %struct.flv_buffer*, %struct.flv_buffer** %c1, align 8, !tbaa !2
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 18) #6
  %d_cur = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %0, i32 0, i32 1
  %1 = load i32, i32* %d_cur, align 4, !tbaa !17
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 0) #6
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 0) #6
  tail call void @flv_put_be32(%struct.flv_buffer* %0, i32 0) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 2) #6
  tail call void @flv_put_amf_string(%struct.flv_buffer* %0, i8* getelementptr inbounds ([11 x i8], [11 x i8]* @.str.1, i32 0, i32 0)) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 8) #6
  tail call void @flv_put_be32(%struct.flv_buffer* %0, i32 7) #6
  tail call void @flv_put_amf_string(%struct.flv_buffer* %0, i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.str.2, i32 0, i32 0)) #6
  %i_width = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 7
  %2 = load i32, i32* %i_width, align 4, !tbaa !18
  %conv = sitofp i32 %2 to double
  tail call void @flv_put_amf_double(%struct.flv_buffer* %0, double %conv) #6
  tail call void @flv_put_amf_string(%struct.flv_buffer* %0, i8* getelementptr inbounds ([7 x i8], [7 x i8]* @.str.3, i32 0, i32 0)) #6
  %i_height = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 8
  %3 = load i32, i32* %i_height, align 8, !tbaa !27
  %conv2 = sitofp i32 %3 to double
  tail call void @flv_put_amf_double(%struct.flv_buffer* %0, double %conv2) #6
  tail call void @flv_put_amf_string(%struct.flv_buffer* %0, i8* getelementptr inbounds ([10 x i8], [10 x i8]* @.str.4, i32 0, i32 0)) #6
  %b_vfr_input = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 62
  %4 = load i32, i32* %b_vfr_input, align 8, !tbaa !28
  %tobool = icmp eq i32 %4, 0
  br i1 %tobool, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %i_fps_num = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 64
  %5 = load i32, i32* %i_fps_num, align 8, !tbaa !29
  %conv3 = uitofp i32 %5 to double
  %i_fps_den = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 65
  %6 = load i32, i32* %i_fps_den, align 4, !tbaa !30
  %conv4 = uitofp i32 %6 to double
  %div = fdiv fast double %conv3, %conv4
  br label %if.end

if.else:                                          ; preds = %entry
  %7 = load i32, i32* %d_cur, align 4, !tbaa !17
  %conv6 = zext i32 %7 to i64
  %d_total = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %0, i32 0, i32 4
  %8 = load i64, i64* %d_total, align 8, !tbaa !31
  %add = add nuw nsw i64 %conv6, 1
  %add7 = add i64 %add, %8
  %i_framerate_pos = getelementptr inbounds i8, i8* %handle, i32 40
  %9 = bitcast i8* %i_framerate_pos to i64*
  store i64 %add7, i64* %9, align 8, !tbaa !32
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %.sink = phi double [ 0.000000e+00, %if.else ], [ %div, %if.then ]
  tail call void @flv_put_amf_double(%struct.flv_buffer* %0, double %.sink) #6
  tail call void @flv_put_amf_string(%struct.flv_buffer* %0, i8* getelementptr inbounds ([13 x i8], [13 x i8]* @.str.5, i32 0, i32 0)) #6
  tail call void @flv_put_amf_double(%struct.flv_buffer* %0, double 7.000000e+00) #6
  tail call void @flv_put_amf_string(%struct.flv_buffer* %0, i8* getelementptr inbounds ([9 x i8], [9 x i8]* @.str.6, i32 0, i32 0)) #6
  %10 = load i32, i32* %d_cur, align 4, !tbaa !17
  %conv9 = zext i32 %10 to i64
  %d_total10 = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %0, i32 0, i32 4
  %11 = load i64, i64* %d_total10, align 8, !tbaa !31
  %add11 = add nuw nsw i64 %conv9, 1
  %add12 = add i64 %add11, %11
  %i_duration_pos = getelementptr inbounds i8, i8* %handle, i32 48
  %12 = bitcast i8* %i_duration_pos to i64*
  store i64 %add12, i64* %12, align 8, !tbaa !33
  tail call void @flv_put_amf_double(%struct.flv_buffer* %0, double 0.000000e+00) #6
  tail call void @flv_put_amf_string(%struct.flv_buffer* %0, i8* getelementptr inbounds ([9 x i8], [9 x i8]* @.str.7, i32 0, i32 0)) #6
  %13 = load i32, i32* %d_cur, align 4, !tbaa !17
  %conv14 = zext i32 %13 to i64
  %14 = load i64, i64* %d_total10, align 8, !tbaa !31
  %add16 = add nuw nsw i64 %conv14, 1
  %add17 = add i64 %add16, %14
  %i_filesize_pos = getelementptr inbounds i8, i8* %handle, i32 56
  %15 = bitcast i8* %i_filesize_pos to i64*
  store i64 %add17, i64* %15, align 8, !tbaa !34
  tail call void @flv_put_amf_double(%struct.flv_buffer* %0, double 0.000000e+00) #6
  tail call void @flv_put_amf_string(%struct.flv_buffer* %0, i8* getelementptr inbounds ([14 x i8], [14 x i8]* @.str.8, i32 0, i32 0)) #6
  %16 = load i32, i32* %d_cur, align 4, !tbaa !17
  %conv19 = zext i32 %16 to i64
  %17 = load i64, i64* %d_total10, align 8, !tbaa !31
  %add21 = add nuw nsw i64 %conv19, 1
  %add22 = add i64 %add21, %17
  %i_bitrate_pos = getelementptr inbounds i8, i8* %handle, i32 64
  %18 = bitcast i8* %i_bitrate_pos to i64*
  store i64 %add22, i64* %18, align 8, !tbaa !35
  tail call void @flv_put_amf_double(%struct.flv_buffer* %0, double 0.000000e+00) #6
  tail call void @flv_put_amf_string(%struct.flv_buffer* %0, i8* getelementptr inbounds ([1 x i8], [1 x i8]* @.str.9, i32 0, i32 0)) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 9) #6
  %19 = load i32, i32* %d_cur, align 4, !tbaa !17
  %sub = sub i32 %19, %1
  %sub24 = add i32 %sub, -10
  tail call void @flv_rewrite_amf_be24(%struct.flv_buffer* %0, i32 %sub24, i32 %1) #6
  %add25 = add i32 %sub, 1
  tail call void @flv_put_be32(%struct.flv_buffer* %0, i32 %add25) #6
  %i_fps_num26 = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 64
  %20 = load i32, i32* %i_fps_num26, align 8, !tbaa !29
  %conv27 = zext i32 %20 to i64
  %i_fps_num28 = getelementptr inbounds i8, i8* %handle, i32 16
  %21 = bitcast i8* %i_fps_num28 to i64*
  store i64 %conv27, i64* %21, align 8, !tbaa !36
  %i_fps_den29 = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 65
  %22 = load i32, i32* %i_fps_den29, align 4, !tbaa !30
  %conv30 = zext i32 %22 to i64
  %i_fps_den31 = getelementptr inbounds i8, i8* %handle, i32 24
  %23 = bitcast i8* %i_fps_den31 to i64*
  store i64 %conv30, i64* %23, align 8, !tbaa !37
  %i_timebase_num = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 66
  %24 = load i32, i32* %i_timebase_num, align 8, !tbaa !38
  %conv32 = uitofp i32 %24 to double
  %i_timebase_den = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 67
  %25 = load i32, i32* %i_timebase_den, align 4, !tbaa !39
  %conv33 = uitofp i32 %25 to double
  %div34 = fdiv fast double %conv32, %conv33
  %d_timebase = getelementptr inbounds i8, i8* %handle, i32 120
  %26 = bitcast i8* %d_timebase to double*
  store double %div34, double* %26, align 8, !tbaa !40
  %27 = load i32, i32* %b_vfr_input, align 8, !tbaa !28
  %b_vfr_input36 = getelementptr inbounds i8, i8* %handle, i32 128
  %28 = bitcast i8* %b_vfr_input36 to i32*
  store i32 %27, i32* %28, align 8, !tbaa !41
  %i_bframe = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 21
  %29 = load i32, i32* %i_bframe, align 4, !tbaa !42
  %tobool37 = icmp eq i32 %29, 0
  br i1 %tobool37, label %cond.end, label %cond.true

cond.true:                                        ; preds = %if.end
  %i_bframe_pyramid = getelementptr inbounds %struct.x264_param_t, %struct.x264_param_t* %p_param, i32 0, i32 24
  %30 = load i32, i32* %i_bframe_pyramid, align 8, !tbaa !43
  %tobool38 = icmp eq i32 %30, 0
  %cond = select i1 %tobool38, i32 1, i32 2
  br label %cond.end

cond.end:                                         ; preds = %if.end, %cond.true
  %cond39 = phi i32 [ %cond, %cond.true ], [ 0, %if.end ]
  %i_delay_frames = getelementptr inbounds i8, i8* %handle, i32 112
  %31 = bitcast i8* %i_delay_frames to i32*
  store i32 %cond39, i32* %31, align 8, !tbaa !44
  ret i32 0
}

; Function Attrs: nounwind
define internal i32 @write_headers(i8* nocapture %handle, %struct.x264_nal_t* nocapture readonly %p_nal) #0 {
entry:
  %c1 = bitcast i8* %handle to %struct.flv_buffer**
  %0 = load %struct.flv_buffer*, %struct.flv_buffer** %c1, align 8, !tbaa !2
  %i_payload = getelementptr inbounds %struct.x264_nal_t, %struct.x264_nal_t* %p_nal, i32 0, i32 5
  %1 = load i32, i32* %i_payload, align 4, !tbaa !45
  %i_payload3 = getelementptr inbounds %struct.x264_nal_t, %struct.x264_nal_t* %p_nal, i32 1, i32 5
  %2 = load i32, i32* %i_payload3, align 4, !tbaa !45
  %i_payload5 = getelementptr inbounds %struct.x264_nal_t, %struct.x264_nal_t* %p_nal, i32 2, i32 5
  %3 = load i32, i32* %i_payload5, align 4, !tbaa !45
  %call = tail call noalias i8* @malloc(i32 %3) #6
  %sei = getelementptr inbounds i8, i8* %handle, i32 4
  %4 = bitcast i8* %sei to i8**
  store i8* %call, i8** %4, align 4, !tbaa !47
  %tobool = icmp eq i8* %call, null
  br i1 %tobool, label %cleanup35, label %if.end

if.end:                                           ; preds = %entry
  %sei_len = getelementptr inbounds i8, i8* %handle, i32 8
  %5 = bitcast i8* %sei_len to i32*
  store i32 %3, i32* %5, align 8, !tbaa !48
  %p_payload = getelementptr inbounds %struct.x264_nal_t, %struct.x264_nal_t* %p_nal, i32 2, i32 6
  %6 = load i8*, i8** %p_payload, align 4, !tbaa !49
  tail call void @llvm.memcpy.p0i8.p0i8.i32(i8* nonnull align 1 %call, i8* align 1 %6, i32 %3, i1 false)
  %p_payload10 = getelementptr inbounds %struct.x264_nal_t, %struct.x264_nal_t* %p_nal, i32 0, i32 6
  %7 = load i8*, i8** %p_payload10, align 4, !tbaa !49
  %add.ptr = getelementptr inbounds i8, i8* %7, i32 4
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 9) #6
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 0) #6
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 0) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 0) #6
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 0) #6
  %d_cur = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %0, i32 0, i32 1
  %8 = load i32, i32* %d_cur, align 4, !tbaa !17
  %start = getelementptr inbounds i8, i8* %handle, i32 136
  %9 = bitcast i8* %start to i32*
  store i32 %8, i32* %9, align 8, !tbaa !50
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 23) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 0) #6
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 0) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 1) #6
  %arrayidx11 = getelementptr inbounds i8, i8* %7, i32 5
  %10 = load i8, i8* %arrayidx11, align 1, !tbaa !51
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext %10) #6
  %arrayidx12 = getelementptr inbounds i8, i8* %7, i32 6
  %11 = load i8, i8* %arrayidx12, align 1, !tbaa !51
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext %11) #6
  %arrayidx13 = getelementptr inbounds i8, i8* %7, i32 7
  %12 = load i8, i8* %arrayidx13, align 1, !tbaa !51
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext %12) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext -1) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext -31) #6
  %sub = add nsw i32 %1, -4
  %conv = trunc i32 %sub to i16
  tail call void @flv_put_be16(%struct.flv_buffer* %0, i16 zeroext %conv) #6
  %call15 = tail call i32 @flv_append_data(%struct.flv_buffer* %0, i8* nonnull %add.ptr, i32 %sub) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 1) #6
  %sub16 = add nsw i32 %2, -4
  %conv17 = trunc i32 %sub16 to i16
  tail call void @flv_put_be16(%struct.flv_buffer* %0, i16 zeroext %conv17) #6
  %p_payload19 = getelementptr inbounds %struct.x264_nal_t, %struct.x264_nal_t* %p_nal, i32 1, i32 6
  %13 = load i8*, i8** %p_payload19, align 4, !tbaa !49
  %add.ptr20 = getelementptr inbounds i8, i8* %13, i32 4
  %call22 = tail call i32 @flv_append_data(%struct.flv_buffer* %0, i8* nonnull %add.ptr20, i32 %sub16) #6
  %14 = load i32, i32* %d_cur, align 4, !tbaa !17
  %15 = load i32, i32* %9, align 8, !tbaa !50
  %sub25 = sub i32 %14, %15
  %sub27 = add i32 %15, -10
  tail call void @flv_rewrite_amf_be24(%struct.flv_buffer* %0, i32 %sub25, i32 %sub27) #6
  %add = add i32 %sub25, 11
  tail call void @flv_put_be32(%struct.flv_buffer* %0, i32 %add) #6
  %call28 = tail call i32 @flv_flush_data(%struct.flv_buffer* %0) #6
  %add32 = add i32 %2, %1
  %add33 = add i32 %add32, %3
  %cmp.inv = icmp sgt i32 %call28, -1
  %retval.0 = select i1 %cmp.inv, i32 %add33, i32 -1
  br label %cleanup35

cleanup35:                                        ; preds = %if.end, %entry
  %retval.1 = phi i32 [ -1, %entry ], [ %retval.0, %if.end ]
  ret i32 %retval.1
}

; Function Attrs: nounwind
define internal i32 @write_frame(i8* %handle, i8* %p_nalu, i32 %i_size, %struct.x264_picture_t* nocapture readonly %p_picture) #0 {
entry:
  %c1 = bitcast i8* %handle to %struct.flv_buffer**
  %0 = load %struct.flv_buffer*, %struct.flv_buffer** %c1, align 8, !tbaa !2
  %i_framenum = getelementptr inbounds i8, i8* %handle, i32 32
  %1 = bitcast i8* %i_framenum to i64*
  %2 = load i64, i64* %1, align 8, !tbaa !52
  %tobool = icmp eq i64 %2, 0
  br i1 %tobool, label %if.then, label %if.end11

if.then:                                          ; preds = %entry
  %i_dts = getelementptr inbounds %struct.x264_picture_t, %struct.x264_picture_t* %p_picture, i32 0, i32 5
  %3 = load i64, i64* %i_dts, align 8, !tbaa !53
  %mul = sub nsw i64 0, %3
  %i_delay_time = getelementptr inbounds i8, i8* %handle, i32 96
  %4 = bitcast i8* %i_delay_time to i64*
  store i64 %mul, i64* %4, align 8, !tbaa !59
  %b_dts_compress = getelementptr inbounds i8, i8* %handle, i32 132
  %5 = bitcast i8* %b_dts_compress to i32*
  %6 = load i32, i32* %5, align 4, !tbaa !12
  %tobool2 = icmp ne i32 %6, 0
  %tobool4 = icmp eq i64 %3, 0
  %or.cond = or i1 %tobool4, %tobool2
  br i1 %or.cond, label %if.end11, label %if.then5

if.then5:                                         ; preds = %if.then
  %i_pts = getelementptr inbounds %struct.x264_picture_t, %struct.x264_picture_t* %p_picture, i32 0, i32 4
  %7 = load i64, i64* %i_pts, align 8, !tbaa !60
  %add = sub i64 %7, %3
  %conv = sitofp i64 %add to double
  %d_timebase = getelementptr inbounds i8, i8* %handle, i32 120
  %8 = bitcast i8* %d_timebase to double*
  %9 = load double, double* %8, align 8, !tbaa !40
  %mul7 = fmul fast double %9, 1.000000e+03
  %mul8 = fmul fast double %mul7, %conv
  %add9 = fadd fast double %mul8, 5.000000e-01
  %conv10 = fptosi double %add9 to i64
  tail call void (i8*, i32, i8*, ...) @x264_cli_log(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.10, i32 0, i32 0), i32 2, i8* getelementptr inbounds ([23 x i8], [23 x i8]* @.str.11, i32 0, i32 0), i64 %conv10) #6
  br label %if.end11

if.end11:                                         ; preds = %entry, %if.then, %if.then5
  %b_dts_compress12 = getelementptr inbounds i8, i8* %handle, i32 132
  %10 = bitcast i8* %b_dts_compress12 to i32*
  %11 = load i32, i32* %10, align 4, !tbaa !12
  %tobool13 = icmp eq i32 %11, 0
  br i1 %tobool13, label %if.else, label %if.then14

if.then14:                                        ; preds = %if.end11
  %12 = load i64, i64* %1, align 8, !tbaa !52
  %cmp = icmp eq i64 %12, 1
  br i1 %cmp, label %if.then17, label %if.end27

if.then17:                                        ; preds = %if.then14
  %i_dts18 = getelementptr inbounds %struct.x264_picture_t, %struct.x264_picture_t* %p_picture, i32 0, i32 5
  %13 = load i64, i64* %i_dts18, align 8, !tbaa !53
  %i_delay_time19 = getelementptr inbounds i8, i8* %handle, i32 96
  %14 = bitcast i8* %i_delay_time19 to i64*
  %15 = load i64, i64* %14, align 8, !tbaa !59
  %add20 = add nsw i64 %15, %13
  %conv21 = sitofp i64 %add20 to double
  %d_timebase22 = getelementptr inbounds i8, i8* %handle, i32 120
  %16 = bitcast i8* %d_timebase22 to double*
  %17 = load double, double* %16, align 8, !tbaa !40
  %mul23 = fmul fast double %17, 1.000000e+03
  %mul24 = fmul fast double %mul23, %conv21
  %add25 = fadd fast double %mul24, 5.000000e-01
  %conv26 = fptosi double %add25 to i64
  %i_init_delta = getelementptr inbounds i8, i8* %handle, i32 104
  %18 = bitcast i8* %i_init_delta to i64*
  store i64 %conv26, i64* %18, align 8, !tbaa !61
  br label %if.end27

if.end27:                                         ; preds = %if.then17, %if.then14
  %i_delay_frames = getelementptr inbounds i8, i8* %handle, i32 112
  %19 = bitcast i8* %i_delay_frames to i32*
  %20 = load i32, i32* %19, align 8, !tbaa !44
  %conv29 = sext i32 %20 to i64
  %cmp30 = icmp sgt i64 %12, %conv29
  br i1 %cmp30, label %cond.true, label %cond.false

cond.true:                                        ; preds = %if.end27
  %i_dts32 = getelementptr inbounds %struct.x264_picture_t, %struct.x264_picture_t* %p_picture, i32 0, i32 5
  %21 = load i64, i64* %i_dts32, align 8, !tbaa !53
  %conv33 = sitofp i64 %21 to double
  %d_timebase34 = getelementptr inbounds i8, i8* %handle, i32 120
  %22 = bitcast i8* %d_timebase34 to double*
  %23 = load double, double* %22, align 8, !tbaa !40
  %mul35 = fmul fast double %conv33, 1.000000e+03
  %mul36 = fmul fast double %mul35, %23
  %add37 = fadd fast double %mul36, 5.000000e-01
  %conv38 = fptosi double %add37 to i64
  br label %cond.end

cond.false:                                       ; preds = %if.end27
  %i_init_delta40 = getelementptr inbounds i8, i8* %handle, i32 104
  %24 = bitcast i8* %i_init_delta40 to i64*
  %25 = load i64, i64* %24, align 8, !tbaa !61
  %mul41 = mul nsw i64 %25, %12
  %add43 = add nsw i32 %20, 1
  %conv44 = sext i32 %add43 to i64
  %div = sdiv i64 %mul41, %conv44
  %d_timebase47.phi.trans.insert = getelementptr inbounds i8, i8* %handle, i32 120
  %.phi.trans.insert = bitcast i8* %d_timebase47.phi.trans.insert to double*
  %.pre = load double, double* %.phi.trans.insert, align 8, !tbaa !40
  br label %cond.end

cond.end:                                         ; preds = %cond.false, %cond.true
  %26 = phi double [ %23, %cond.true ], [ %.pre, %cond.false ]
  %cond = phi i64 [ %conv38, %cond.true ], [ %div, %cond.false ]
  %i_pts45 = getelementptr inbounds %struct.x264_picture_t, %struct.x264_picture_t* %p_picture, i32 0, i32 4
  %27 = load i64, i64* %i_pts45, align 8, !tbaa !60
  %conv46 = sitofp i64 %27 to double
  %mul48 = fmul fast double %26, %conv46
  br label %if.end70

if.else:                                          ; preds = %if.end11
  %i_dts52 = getelementptr inbounds %struct.x264_picture_t, %struct.x264_picture_t* %p_picture, i32 0, i32 5
  %28 = load i64, i64* %i_dts52, align 8, !tbaa !53
  %i_delay_time53 = getelementptr inbounds i8, i8* %handle, i32 96
  %29 = bitcast i8* %i_delay_time53 to i64*
  %30 = load i64, i64* %29, align 8, !tbaa !59
  %add54 = add nsw i64 %30, %28
  %conv55 = sitofp i64 %add54 to double
  %d_timebase56 = getelementptr inbounds i8, i8* %handle, i32 120
  %31 = bitcast i8* %d_timebase56 to double*
  %32 = load double, double* %31, align 8, !tbaa !40
  %mul57 = fmul fast double %32, 1.000000e+03
  %mul58 = fmul fast double %mul57, %conv55
  %add59 = fadd fast double %mul58, 5.000000e-01
  %conv60 = fptosi double %add59 to i64
  %i_pts61 = getelementptr inbounds %struct.x264_picture_t, %struct.x264_picture_t* %p_picture, i32 0, i32 4
  %33 = load i64, i64* %i_pts61, align 8, !tbaa !60
  %add63 = add nsw i64 %33, %30
  %conv64 = sitofp i64 %add63 to double
  %mul66 = fmul fast double %32, %conv64
  %.pre189 = load i64, i64* %1, align 8, !tbaa !52
  br label %if.end70

if.end70:                                         ; preds = %if.else, %cond.end
  %34 = phi i64 [ %12, %cond.end ], [ %.pre189, %if.else ]
  %cts.0.in.in.in = phi double [ %mul48, %cond.end ], [ %mul66, %if.else ]
  %dts.0 = phi i64 [ %cond, %cond.end ], [ %conv60, %if.else ]
  %cts.0.in.in = fmul fast double %cts.0.in.in.in, 1.000000e+03
  %cts.0.in = fadd fast double %cts.0.in.in, 5.000000e-01
  %cts.0 = fptosi double %cts.0.in to i64
  %sub = sub nsw i64 %cts.0, %dts.0
  %tobool72 = icmp eq i64 %34, 0
  br i1 %tobool72, label %if.end82, label %if.then73

if.then73:                                        ; preds = %if.end70
  %i_prev_dts = getelementptr inbounds i8, i8* %handle, i32 80
  %35 = bitcast i8* %i_prev_dts to i64*
  %36 = load i64, i64* %35, align 8, !tbaa !62
  %cmp74 = icmp eq i64 %36, %dts.0
  br i1 %cmp74, label %if.then76, label %if.end77

if.then76:                                        ; preds = %if.then73
  tail call void (i8*, i32, i8*, ...) @x264_cli_log(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.10, i32 0, i32 0), i32 1, i8* getelementptr inbounds ([98 x i8], [98 x i8]* @.str.12, i32 0, i32 0), i64 %dts.0) #6
  br label %if.end77

if.end77:                                         ; preds = %if.then76, %if.then73
  %i_prev_cts = getelementptr inbounds i8, i8* %handle, i32 88
  %37 = bitcast i8* %i_prev_cts to i64*
  %38 = load i64, i64* %37, align 8, !tbaa !63
  %cmp78 = icmp eq i64 %38, %cts.0
  br i1 %cmp78, label %if.then80, label %if.end82

if.then80:                                        ; preds = %if.end77
  tail call void (i8*, i32, i8*, ...) @x264_cli_log(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.10, i32 0, i32 0), i32 1, i8* getelementptr inbounds ([101 x i8], [101 x i8]* @.str.13, i32 0, i32 0), i64 %cts.0) #6
  br label %if.end82

if.end82:                                         ; preds = %if.end70, %if.end77, %if.then80
  %i_prev_dts83 = getelementptr inbounds i8, i8* %handle, i32 80
  %39 = bitcast i8* %i_prev_dts83 to i64*
  store i64 %dts.0, i64* %39, align 8, !tbaa !62
  %i_prev_cts84 = getelementptr inbounds i8, i8* %handle, i32 88
  %40 = bitcast i8* %i_prev_cts84 to i64*
  store i64 %cts.0, i64* %40, align 8, !tbaa !63
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 9) #6
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 0) #6
  %conv85 = trunc i64 %dts.0 to i32
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 %conv85) #6
  %41 = lshr i64 %dts.0, 24
  %conv86 = trunc i64 %41 to i8
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext %conv86) #6
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 0) #6
  %d_cur = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %0, i32 0, i32 1
  %42 = load i32, i32* %d_cur, align 4, !tbaa !17
  %start = getelementptr inbounds i8, i8* %handle, i32 136
  %43 = bitcast i8* %start to i32*
  store i32 %42, i32* %43, align 8, !tbaa !50
  %b_keyframe = getelementptr inbounds %struct.x264_picture_t, %struct.x264_picture_t* %p_picture, i32 0, i32 3
  %44 = load i32, i32* %b_keyframe, align 4, !tbaa !64
  %tobool87 = icmp eq i32 %44, 0
  %or = select i1 %tobool87, i8 39, i8 23
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext %or) #6
  tail call void @flv_put_byte(%struct.flv_buffer* %0, i8 zeroext 1) #6
  %conv90 = trunc i64 %sub to i32
  tail call void @flv_put_be24(%struct.flv_buffer* %0, i32 %conv90) #6
  %sei = getelementptr inbounds i8, i8* %handle, i32 4
  %45 = bitcast i8* %sei to i8**
  %46 = load i8*, i8** %45, align 4, !tbaa !47
  %tobool91 = icmp eq i8* %46, null
  br i1 %tobool91, label %if.end96, label %if.then92

if.then92:                                        ; preds = %if.end82
  %sei_len = getelementptr inbounds i8, i8* %handle, i32 8
  %47 = bitcast i8* %sei_len to i32*
  %48 = load i32, i32* %47, align 8, !tbaa !48
  %call = tail call i32 @flv_append_data(%struct.flv_buffer* nonnull %0, i8* nonnull %46, i32 %48) #6
  %49 = load i8*, i8** %45, align 4, !tbaa !47
  tail call void @free(i8* %49) #6
  store i8* null, i8** %45, align 4, !tbaa !47
  br label %if.end96

if.end96:                                         ; preds = %if.end82, %if.then92
  %call97 = tail call i32 @flv_append_data(%struct.flv_buffer* nonnull %0, i8* %p_nalu, i32 %i_size) #6
  %50 = load i32, i32* %d_cur, align 4, !tbaa !17
  %51 = load i32, i32* %43, align 8, !tbaa !50
  %sub100 = sub i32 %50, %51
  %sub102 = add i32 %51, -10
  tail call void @flv_rewrite_amf_be24(%struct.flv_buffer* nonnull %0, i32 %sub100, i32 %sub102) #6
  %add103 = add i32 %sub100, 11
  tail call void @flv_put_be32(%struct.flv_buffer* nonnull %0, i32 %add103) #6
  %call104 = tail call i32 @flv_flush_data(%struct.flv_buffer* nonnull %0) #6
  %cmp105 = icmp slt i32 %call104, 0
  br i1 %cmp105, label %cleanup, label %do.end

do.end:                                           ; preds = %if.end96
  %52 = load i64, i64* %1, align 8, !tbaa !52
  %inc = add nsw i64 %52, 1
  store i64 %inc, i64* %1, align 8, !tbaa !52
  br label %cleanup

cleanup:                                          ; preds = %if.end96, %do.end
  %retval.0 = phi i32 [ %i_size, %do.end ], [ -1, %if.end96 ]
  ret i32 %retval.0
}

; Function Attrs: nounwind
define internal i32 @close_file(i8* nocapture %handle, i64 %largest_pts, i64 %second_largest_pts) #0 {
entry:
  %x.i146 = alloca i64, align 8
  %x.i127 = alloca i64, align 8
  %x.i108 = alloca i64, align 8
  %x.i = alloca i64, align 8
  %file_stat.i = alloca %struct.stat, align 8
  %c1 = bitcast i8* %handle to %struct.flv_buffer**
  %0 = load %struct.flv_buffer*, %struct.flv_buffer** %c1, align 8, !tbaa !2
  %call = tail call i32 @flv_flush_data(%struct.flv_buffer* %0) #6
  %cmp = icmp slt i32 %call, 0
  br i1 %cmp, label %error, label %do.end

do.end:                                           ; preds = %entry
  %i_framenum = getelementptr inbounds i8, i8* %handle, i32 32
  %1 = bitcast i8* %i_framenum to i64*
  %2 = load i64, i64* %1, align 8, !tbaa !52
  %cmp2 = icmp eq i64 %2, 1
  br i1 %cmp2, label %if.then3, label %if.else

if.then3:                                         ; preds = %do.end
  %i_fps_num = getelementptr inbounds i8, i8* %handle, i32 16
  %3 = bitcast i8* %i_fps_num to i64*
  %4 = load i64, i64* %3, align 8, !tbaa !36
  %tobool = icmp eq i64 %4, 0
  br i1 %tobool, label %if.end8, label %cond.true

cond.true:                                        ; preds = %if.then3
  %i_fps_den = getelementptr inbounds i8, i8* %handle, i32 24
  %5 = bitcast i8* %i_fps_den to i64*
  %6 = load i64, i64* %5, align 8, !tbaa !37
  %conv = sitofp i64 %6 to double
  %conv5 = sitofp i64 %4 to double
  %div = fdiv fast double %conv, %conv5
  br label %if.end8

if.else:                                          ; preds = %do.end
  %mul = shl nsw i64 %largest_pts, 1
  %sub = sub nsw i64 %mul, %second_largest_pts
  %conv6 = sitofp i64 %sub to double
  %d_timebase = getelementptr inbounds i8, i8* %handle, i32 120
  %7 = bitcast i8* %d_timebase to double*
  %8 = load double, double* %7, align 8, !tbaa !40
  %mul7 = fmul fast double %8, %conv6
  br label %if.end8

if.end8:                                          ; preds = %cond.true, %if.then3, %if.else
  %total_duration.0 = phi double [ %mul7, %if.else ], [ %div, %cond.true ], [ 0.000000e+00, %if.then3 ]
  %fp = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %0, i32 0, i32 3
  %9 = load %struct._IO_FILE*, %struct._IO_FILE** %fp, align 4, !tbaa !13
  %10 = bitcast %struct.stat* %file_stat.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 104, i8* nonnull %10) #6
  %call.i = tail call i32 @fileno(%struct._IO_FILE* %9) #6
  %11 = bitcast %struct.stat* %file_stat.i to %struct.stat64*
  %call.i.i = call i32 @__fxstat64(i32 3, i32 %call.i, %struct.stat64* nonnull %11) #6
  %tobool.i = icmp ne i32 %call.i.i, 0
  %st_mode.i = getelementptr inbounds %struct.stat, %struct.stat* %file_stat.i, i32 0, i32 3
  %12 = load i32, i32* %st_mode.i, align 8
  %and.i = and i32 %12, 61440
  %cmp.i = icmp eq i32 %and.i, 32768
  %narrow.i = or i1 %tobool.i, %cmp.i
  call void @llvm.lifetime.end.p0i8(i64 104, i8* nonnull %10) #6
  %cmp11 = fcmp fast ogt double %total_duration.0, 0.000000e+00
  %or.cond = and i1 %cmp11, %narrow.i
  br i1 %or.cond, label %if.then13, label %error

if.then13:                                        ; preds = %if.end8
  %13 = load %struct._IO_FILE*, %struct._IO_FILE** %fp, align 4, !tbaa !13
  %call15 = call i32 @ftell(%struct._IO_FILE* %13)
  %i_framerate_pos = getelementptr inbounds i8, i8* %handle, i32 40
  %14 = bitcast i8* %i_framerate_pos to i64*
  %15 = load i64, i64* %14, align 8, !tbaa !32
  %tobool17 = icmp eq i64 %15, 0
  br i1 %tobool17, label %do.body33, label %if.then18

if.then18:                                        ; preds = %if.then13
  %16 = load i64, i64* %1, align 8, !tbaa !52
  %conv20 = sitofp i64 %16 to double
  %div21 = fdiv fast double %conv20, %total_duration.0
  %17 = load %struct._IO_FILE*, %struct._IO_FILE** %fp, align 4, !tbaa !13
  %18 = bitcast i64* %x.i to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %18) #6
  %call.i105 = call i64 @flv_dbl2int(double %div21) #6
  %shr.i.i = lshr i64 %call.i105, 32
  %conv.i.i = trunc i64 %shr.i.i to i32
  %add5.i.i.i = call i32 @llvm.bswap.i32(i32 %conv.i.i) #6
  %conv1.i.i = zext i32 %add5.i.i.i to i64
  %conv2.i.i = trunc i64 %call.i105 to i32
  %add5.i6.i.i = call i32 @llvm.bswap.i32(i32 %conv2.i.i) #6
  %conv4.i.i = zext i32 %add5.i6.i.i to i64
  %shl.i.i = shl nuw i64 %conv4.i.i, 32
  %add.i.i = or i64 %shl.i.i, %conv1.i.i
  store i64 %add.i.i, i64* %x.i, align 8, !tbaa !65
  %conv.i = trunc i64 %15 to i32
  %call2.i = call i32 @fseek(%struct._IO_FILE* %17, i32 %conv.i, i32 0) #6
  %tobool.i106 = icmp eq i32 %call2.i, 0
  br i1 %tobool.i106, label %rewrite_amf_double.exit, label %rewrite_amf_double.exit.thread

rewrite_amf_double.exit.thread:                   ; preds = %if.then18
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %18) #6
  br label %cleanup.thread

rewrite_amf_double.exit:                          ; preds = %if.then18
  %call3.i = call i32 @fwrite(i8* nonnull %18, i32 8, i32 1, %struct._IO_FILE* %17) #6
  %cmp.i107 = icmp eq i32 %call3.i, 1
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %18) #6
  br i1 %cmp.i107, label %do.body33, label %cleanup.thread

do.body33:                                        ; preds = %rewrite_amf_double.exit, %if.then13
  %19 = load %struct._IO_FILE*, %struct._IO_FILE** %fp, align 4, !tbaa !13
  %i_duration_pos = getelementptr inbounds i8, i8* %handle, i32 48
  %20 = bitcast i8* %i_duration_pos to i64*
  %21 = load i64, i64* %20, align 8, !tbaa !33
  %22 = bitcast i64* %x.i108 to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %22) #6
  %call.i109 = call i64 @flv_dbl2int(double %total_duration.0) #6
  %shr.i.i110 = lshr i64 %call.i109, 32
  %conv.i.i111 = trunc i64 %shr.i.i110 to i32
  %add5.i.i.i112 = call i32 @llvm.bswap.i32(i32 %conv.i.i111) #6
  %conv1.i.i113 = zext i32 %add5.i.i.i112 to i64
  %conv2.i.i114 = trunc i64 %call.i109 to i32
  %add5.i6.i.i115 = call i32 @llvm.bswap.i32(i32 %conv2.i.i114) #6
  %conv4.i.i116 = zext i32 %add5.i6.i.i115 to i64
  %shl.i.i117 = shl nuw i64 %conv4.i.i116, 32
  %add.i.i118 = or i64 %shl.i.i117, %conv1.i.i113
  store i64 %add.i.i118, i64* %x.i108, align 8, !tbaa !65
  %conv.i119 = trunc i64 %21 to i32
  %call2.i120 = call i32 @fseek(%struct._IO_FILE* %19, i32 %conv.i119, i32 0) #6
  %tobool.i121 = icmp eq i32 %call2.i120, 0
  br i1 %tobool.i121, label %rewrite_amf_double.exit126, label %rewrite_amf_double.exit126.thread

rewrite_amf_double.exit126.thread:                ; preds = %do.body33
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %22) #6
  br label %cleanup.thread

rewrite_amf_double.exit126:                       ; preds = %do.body33
  %call3.i122 = call i32 @fwrite(i8* nonnull %22, i32 8, i32 1, %struct._IO_FILE* %19) #6
  %cmp.i123 = icmp eq i32 %call3.i122, 1
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %22) #6
  br i1 %cmp.i123, label %do.body42, label %cleanup.thread

do.body42:                                        ; preds = %rewrite_amf_double.exit126
  %23 = load %struct._IO_FILE*, %struct._IO_FILE** %fp, align 4, !tbaa !13
  %i_filesize_pos = getelementptr inbounds i8, i8* %handle, i32 56
  %24 = bitcast i8* %i_filesize_pos to i64*
  %25 = load i64, i64* %24, align 8, !tbaa !34
  %conv44 = sitofp i32 %call15 to double
  %26 = bitcast i64* %x.i127 to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %26) #6
  %call.i128 = call i64 @flv_dbl2int(double %conv44) #6
  %shr.i.i129 = lshr i64 %call.i128, 32
  %conv.i.i130 = trunc i64 %shr.i.i129 to i32
  %add5.i.i.i131 = call i32 @llvm.bswap.i32(i32 %conv.i.i130) #6
  %conv1.i.i132 = zext i32 %add5.i.i.i131 to i64
  %conv2.i.i133 = trunc i64 %call.i128 to i32
  %add5.i6.i.i134 = call i32 @llvm.bswap.i32(i32 %conv2.i.i133) #6
  %conv4.i.i135 = zext i32 %add5.i6.i.i134 to i64
  %shl.i.i136 = shl nuw i64 %conv4.i.i135, 32
  %add.i.i137 = or i64 %shl.i.i136, %conv1.i.i132
  store i64 %add.i.i137, i64* %x.i127, align 8, !tbaa !65
  %conv.i138 = trunc i64 %25 to i32
  %call2.i139 = call i32 @fseek(%struct._IO_FILE* %23, i32 %conv.i138, i32 0) #6
  %tobool.i140 = icmp eq i32 %call2.i139, 0
  br i1 %tobool.i140, label %rewrite_amf_double.exit145, label %rewrite_amf_double.exit145.thread

rewrite_amf_double.exit145.thread:                ; preds = %do.body42
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %26) #6
  br label %cleanup.thread

rewrite_amf_double.exit145:                       ; preds = %do.body42
  %call3.i141 = call i32 @fwrite(i8* nonnull %26, i32 8, i32 1, %struct._IO_FILE* %23) #6
  %cmp.i142 = icmp eq i32 %call3.i141, 1
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %26) #6
  br i1 %cmp.i142, label %do.body52, label %cleanup.thread

do.body52:                                        ; preds = %rewrite_amf_double.exit145
  %27 = load %struct._IO_FILE*, %struct._IO_FILE** %fp, align 4, !tbaa !13
  %i_bitrate_pos = getelementptr inbounds i8, i8* %handle, i32 64
  %28 = bitcast i8* %i_bitrate_pos to i64*
  %29 = load i64, i64* %28, align 8, !tbaa !35
  %mul55 = fmul fast double %conv44, 8.000000e+00
  %mul56 = fmul fast double %total_duration.0, 1.000000e+03
  %div57 = fdiv fast double %mul55, %mul56
  %30 = bitcast i64* %x.i146 to i8*
  call void @llvm.lifetime.start.p0i8(i64 8, i8* nonnull %30) #6
  %call.i147 = call i64 @flv_dbl2int(double %div57) #6
  %shr.i.i148 = lshr i64 %call.i147, 32
  %conv.i.i149 = trunc i64 %shr.i.i148 to i32
  %add5.i.i.i150 = call i32 @llvm.bswap.i32(i32 %conv.i.i149) #6
  %conv1.i.i151 = zext i32 %add5.i.i.i150 to i64
  %conv2.i.i152 = trunc i64 %call.i147 to i32
  %add5.i6.i.i153 = call i32 @llvm.bswap.i32(i32 %conv2.i.i152) #6
  %conv4.i.i154 = zext i32 %add5.i6.i.i153 to i64
  %shl.i.i155 = shl nuw i64 %conv4.i.i154, 32
  %add.i.i156 = or i64 %shl.i.i155, %conv1.i.i151
  store i64 %add.i.i156, i64* %x.i146, align 8, !tbaa !65
  %conv.i157 = trunc i64 %29 to i32
  %call2.i158 = call i32 @fseek(%struct._IO_FILE* %27, i32 %conv.i157, i32 0) #6
  %tobool.i159 = icmp eq i32 %call2.i158, 0
  br i1 %tobool.i159, label %rewrite_amf_double.exit164, label %rewrite_amf_double.exit164.thread

rewrite_amf_double.exit164.thread:                ; preds = %do.body52
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %30) #6
  br label %cleanup.thread

rewrite_amf_double.exit164:                       ; preds = %do.body52
  %call3.i160 = call i32 @fwrite(i8* nonnull %30, i32 8, i32 1, %struct._IO_FILE* %27) #6
  %cmp.i161 = icmp eq i32 %call3.i160, 1
  call void @llvm.lifetime.end.p0i8(i64 8, i8* nonnull %30) #6
  br i1 %cmp.i161, label %error, label %cleanup.thread

cleanup.thread:                                   ; preds = %rewrite_amf_double.exit164, %rewrite_amf_double.exit145, %rewrite_amf_double.exit126, %rewrite_amf_double.exit, %rewrite_amf_double.exit.thread, %rewrite_amf_double.exit126.thread, %rewrite_amf_double.exit145.thread, %rewrite_amf_double.exit164.thread
  br label %error

error:                                            ; preds = %rewrite_amf_double.exit164, %if.end8, %cleanup.thread, %entry
  %ret.0 = phi i32 [ -1, %entry ], [ -1, %cleanup.thread ], [ 0, %rewrite_amf_double.exit164 ], [ 0, %if.end8 ]
  %fp67 = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %0, i32 0, i32 3
  %31 = load %struct._IO_FILE*, %struct._IO_FILE** %fp67, align 4, !tbaa !13
  %call68 = call i32 @fclose(%struct._IO_FILE* %31)
  %data = getelementptr inbounds %struct.flv_buffer, %struct.flv_buffer* %0, i32 0, i32 0
  %32 = load i8*, i8** %data, align 8, !tbaa !15
  call void @free(i8* %32) #6
  %33 = bitcast %struct.flv_buffer* %0 to i8*
  call void @free(i8* %33) #6
  call void @free(i8* nonnull %handle) #6
  ret i32 %ret.0
}

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #1

; Function Attrs: nofree nounwind
declare dso_local noalias i8* @calloc(i32, i32) local_unnamed_addr #2

declare dso_local %struct.flv_buffer* @flv_create_writer(i8*) local_unnamed_addr #3

; Function Attrs: nofree nounwind
declare dso_local i32 @fclose(%struct._IO_FILE* nocapture) local_unnamed_addr #2

; Function Attrs: nounwind
declare dso_local void @free(i8* nocapture) local_unnamed_addr #4

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #1

declare dso_local void @flv_put_tag(%struct.flv_buffer*, i8*) local_unnamed_addr #3

declare dso_local void @flv_put_byte(%struct.flv_buffer*, i8 zeroext) local_unnamed_addr #3

declare dso_local void @flv_put_be32(%struct.flv_buffer*, i32) local_unnamed_addr #3

declare dso_local i32 @flv_flush_data(%struct.flv_buffer*) local_unnamed_addr #3

declare dso_local void @flv_put_be24(%struct.flv_buffer*, i32) local_unnamed_addr #3

declare dso_local void @flv_put_amf_string(%struct.flv_buffer*, i8*) local_unnamed_addr #3

declare dso_local void @flv_put_amf_double(%struct.flv_buffer*, double) local_unnamed_addr #3

declare dso_local void @flv_rewrite_amf_be24(%struct.flv_buffer*, i32, i32) local_unnamed_addr #3

; Function Attrs: nofree nounwind
declare dso_local noalias i8* @malloc(i32) local_unnamed_addr #2

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.memcpy.p0i8.p0i8.i32(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i32, i1 immarg) #1

declare dso_local void @flv_put_be16(%struct.flv_buffer*, i16 zeroext) local_unnamed_addr #3

declare dso_local i32 @flv_append_data(%struct.flv_buffer*, i8*, i32) local_unnamed_addr #3

declare dso_local void @x264_cli_log(i8*, i32, i8*, ...) local_unnamed_addr #3

; Function Attrs: nofree nounwind
declare dso_local i32 @ftell(%struct._IO_FILE* nocapture) local_unnamed_addr #2

; Function Attrs: nofree nounwind
declare dso_local i32 @fileno(%struct._IO_FILE* nocapture) local_unnamed_addr #2

; Function Attrs: nounwind
declare dso_local i32 @__fxstat64(i32, i32, %struct.stat64*) local_unnamed_addr #4

declare dso_local i64 @flv_dbl2int(double) local_unnamed_addr #3

; Function Attrs: nofree nounwind
declare dso_local i32 @fseek(%struct._IO_FILE* nocapture, i32, i32) local_unnamed_addr #2

; Function Attrs: nofree nounwind
declare dso_local i32 @fwrite(i8* nocapture, i32, i32, %struct._IO_FILE* nocapture) local_unnamed_addr #2

; Function Attrs: nounwind readnone speculatable willreturn
declare i32 @llvm.bswap.i32(i32) #5

attributes #0 = { nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="true" "no-jump-tables"="false" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="dspse" "unsafe-fp-math"="true" "use-soft-float"="false" }
attributes #1 = { argmemonly nounwind willreturn }
attributes #2 = { nofree nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="dspse" "unsafe-fp-math"="true" "use-soft-float"="false" }
attributes #3 = { "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="dspse" "unsafe-fp-math"="true" "use-soft-float"="false" }
attributes #4 = { nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="dspse" "unsafe-fp-math"="true" "use-soft-float"="false" }
attributes #5 = { nounwind readnone speculatable willreturn }
attributes #6 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.0 (http://10.18.30.194:8888/compiler/compiler10.git 713ef477716300a9b04a1522e3fce445623444dc)"}
!2 = !{!3, !4, i64 0}
!3 = !{!"", !4, i64 0, !4, i64 4, !7, i64 8, !8, i64 16, !8, i64 24, !8, i64 32, !8, i64 40, !8, i64 48, !8, i64 56, !8, i64 64, !5, i64 72, !8, i64 80, !8, i64 88, !8, i64 96, !8, i64 104, !7, i64 112, !9, i64 120, !7, i64 128, !7, i64 132, !7, i64 136}
!4 = !{!"any pointer", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C/C++ TBAA"}
!7 = !{!"int", !5, i64 0}
!8 = !{!"long long", !5, i64 0}
!9 = !{!"double", !5, i64 0}
!10 = !{!11, !7, i64 0}
!11 = !{!"", !7, i64 0}
!12 = !{!3, !7, i64 132}
!13 = !{!14, !4, i64 12}
!14 = !{!"flv_buffer", !4, i64 0, !7, i64 4, !7, i64 8, !4, i64 12, !8, i64 16}
!15 = !{!14, !4, i64 0}
!16 = !{!4, !4, i64 0}
!17 = !{!14, !7, i64 4}
!18 = !{!19, !7, i64 28}
!19 = !{!"x264_param_t", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12, !7, i64 16, !7, i64 20, !7, i64 24, !7, i64 28, !7, i64 32, !7, i64 36, !7, i64 40, !7, i64 44, !7, i64 48, !7, i64 52, !20, i64 56, !7, i64 92, !7, i64 96, !7, i64 100, !7, i64 104, !7, i64 108, !7, i64 112, !7, i64 116, !7, i64 120, !7, i64 124, !7, i64 128, !7, i64 132, !7, i64 136, !7, i64 140, !7, i64 144, !7, i64 148, !7, i64 152, !7, i64 156, !7, i64 160, !7, i64 164, !7, i64 168, !7, i64 172, !7, i64 176, !4, i64 180, !5, i64 184, !5, i64 200, !5, i64 216, !5, i64 232, !5, i64 248, !5, i64 312, !5, i64 376, !5, i64 440, !4, i64 504, !4, i64 508, !7, i64 512, !7, i64 516, !4, i64 520, !21, i64 524, !23, i64 632, !24, i64 748, !7, i64 764, !25, i64 768, !26, i64 824, !7, i64 836, !7, i64 840, !7, i64 844, !7, i64 848, !7, i64 852, !7, i64 856, !7, i64 860, !7, i64 864, !7, i64 868, !7, i64 872, !7, i64 876, !7, i64 880, !7, i64 884, !7, i64 888, !7, i64 892, !7, i64 896, !7, i64 900, !4, i64 904, !4, i64 908, !7, i64 912, !7, i64 916, !7, i64 920, !7, i64 924, !7, i64 928, !4, i64 932, !4, i64 936, !4, i64 940}
!20 = !{!"", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12, !7, i64 16, !7, i64 20, !7, i64 24, !7, i64 28, !7, i64 32}
!21 = !{!"", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12, !7, i64 16, !7, i64 20, !7, i64 24, !7, i64 28, !7, i64 32, !7, i64 36, !7, i64 40, !7, i64 44, !7, i64 48, !7, i64 52, !7, i64 56, !7, i64 60, !7, i64 64, !7, i64 68, !22, i64 72, !22, i64 76, !7, i64 80, !7, i64 84, !7, i64 88, !5, i64 92, !7, i64 100, !7, i64 104}
!22 = !{!"float", !5, i64 0}
!23 = !{!"", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12, !7, i64 16, !7, i64 20, !22, i64 24, !22, i64 28, !22, i64 32, !7, i64 36, !7, i64 40, !22, i64 44, !22, i64 48, !22, i64 52, !7, i64 56, !7, i64 60, !22, i64 64, !7, i64 68, !7, i64 72, !7, i64 76, !4, i64 80, !7, i64 84, !4, i64 88, !22, i64 92, !22, i64 96, !22, i64 100, !4, i64 104, !7, i64 108, !4, i64 112}
!24 = !{!"", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12}
!25 = !{!"", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12, !7, i64 16, !7, i64 20, !7, i64 24, !7, i64 28, !7, i64 32, !8, i64 40, !8, i64 48}
!26 = !{!"", !7, i64 0, !7, i64 4, !7, i64 8}
!27 = !{!19, !7, i64 32}
!28 = !{!19, !7, i64 856}
!29 = !{!19, !7, i64 864}
!30 = !{!19, !7, i64 868}
!31 = !{!14, !8, i64 16}
!32 = !{!3, !8, i64 40}
!33 = !{!3, !8, i64 48}
!34 = !{!3, !8, i64 56}
!35 = !{!3, !8, i64 64}
!36 = !{!3, !8, i64 16}
!37 = !{!3, !8, i64 24}
!38 = !{!19, !7, i64 872}
!39 = !{!19, !7, i64 876}
!40 = !{!3, !9, i64 120}
!41 = !{!3, !7, i64 128}
!42 = !{!19, !7, i64 116}
!43 = !{!19, !7, i64 128}
!44 = !{!3, !7, i64 112}
!45 = !{!46, !7, i64 20}
!46 = !{!"x264_nal_t", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12, !7, i64 16, !7, i64 20, !4, i64 24, !7, i64 28}
!47 = !{!3, !4, i64 4}
!48 = !{!3, !7, i64 8}
!49 = !{!46, !4, i64 24}
!50 = !{!3, !7, i64 136}
!51 = !{!5, !5, i64 0}
!52 = !{!3, !8, i64 32}
!53 = !{!54, !8, i64 24}
!54 = !{!"x264_picture_t", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12, !8, i64 16, !8, i64 24, !4, i64 32, !55, i64 36, !56, i64 80, !57, i64 144, !58, i64 176, !4, i64 188}
!55 = !{!"x264_image_t", !7, i64 0, !7, i64 4, !5, i64 8, !5, i64 24}
!56 = !{!"x264_image_properties_t", !4, i64 0, !4, i64 4, !4, i64 8, !4, i64 12, !9, i64 16, !9, i64 24, !5, i64 32, !9, i64 56}
!57 = !{!"x264_hrd_t", !9, i64 0, !9, i64 8, !9, i64 16, !9, i64 24}
!58 = !{!"x264_sei_t", !7, i64 0, !4, i64 4, !4, i64 8}
!59 = !{!3, !8, i64 96}
!60 = !{!54, !8, i64 16}
!61 = !{!3, !8, i64 104}
!62 = !{!3, !8, i64 80}
!63 = !{!3, !8, i64 88}
!64 = !{!54, !7, i64 12}
!65 = !{!8, !8, i64 0}
